/**
 * Pure credential and env utility functions.
 * Extracted here so they can be unit-tested independently of the server.
 */

// ── Sensitive key detection ──────────────────────────────────────────────────

export const SENSITIVE_PATTERNS = [
  /PASSWORD/i, /TOKEN/i, /SECRET/i, /API_KEY/i, /PRIVATE_KEY/i, /AUTH_TOKEN/i,
];

export const SENSITIVE_KEYS = new Set([
  "SF_PASSWORD", "SF_EMAIL_CODE", "AWS_PASSWORD",
  "TWILIO_AUTH_TOKEN", "VAULT_TOKEN", "SF_OAUTH_CONSUMER_SECRET",
  "GEMINI_API_KEY",
]);

export const NON_SENSITIVE_KEYS = new Set(["SECRETS_BACKEND", "REGULATED_MODE"]);

export function isSensitiveKey(key) {
  if (NON_SENSITIVE_KEYS.has(key)) return false;
  if (SENSITIVE_KEYS.has(key)) return true;
  if (key.endsWith("_REF")) return false; // Vault refs are not sensitive
  return SENSITIVE_PATTERNS.some((p) => p.test(key));
}

export function isBulletMasked(value) {
  return typeof value === "string" && value.startsWith("\u2022");
}

export function maskSensitiveValues(envMap) {
  const masked = { ...envMap };
  for (const key of Object.keys(masked)) {
    if (isSensitiveKey(key) && masked[key]) {
      masked[key] = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
    }
  }
  return masked;
}

// ── Vault secret groups (matches vault-seed.sh conventions) ─────────────────

export const VAULT_SECRET_GROUPS = {
  salesforce: {
    subpath: "salesforce",
    fields: {
      sfUsername: "username",
      sfPassword: "password",
      oauthConsumerKey: "consumer_key",
      oauthConsumerSecret: "consumer_secret",
    },
  },
  aws: {
    subpath: "aws",
    fields: {
      awsUsername: "username",
      awsPassword: "password",
      awsAccountId: "account_id",
      awsAccessKeyId: "access_key_id",
      awsSecretAccessKey: "secret_access_key",
      connectInstanceId: "connect_instance_id",
    },
  },
  twilio: {
    subpath: "twilio",
    fields: {
      twilioSid: "account_sid",
      twilioToken: "auth_token",
    },
  },
  gemini: {
    subpath: "gemini",
    fields: {
      geminiApiKey: "api_key",
    },
  },
};

/**
 * Build _REF values from a Vault base path using grouped subpaths.
 * e.g. basePath="secret/data/voice/personal"
 *   → { oauthConsumerKeyRef: "secret/data/voice/personal/salesforce#consumer_key", ... }
 */
export function buildVaultRefsFromBasePath(basePath) {
  const refs = {};
  const base = basePath.replace(/\/+$/, "");
  for (const group of Object.values(VAULT_SECRET_GROUPS)) {
    for (const [credKey, vaultField] of Object.entries(group.fields)) {
      refs[credKey + "Ref"] = `${base}/${group.subpath}#${vaultField}`;
    }
  }
  return refs;
}

/**
 * Resolve a single Vault ref string to its plaintext value.
 * Ref format: "secret/data/path/to/secret#field_name"
 */
export async function resolveVaultRef(ref, vaultAddr, vaultToken) {
  if (!ref || !vaultAddr || !vaultToken) return null;
  if (isBulletMasked(vaultToken)) return null; // never use a masked token
  const hashIdx = ref.lastIndexOf("#");
  if (hashIdx < 0) return null;
  const secretPath = ref.slice(0, hashIdx).replace(/^\/+/, "");
  const field = ref.slice(hashIdx + 1);
  try {
    const resp = await fetch(`${vaultAddr.replace(/\/+$/, "")}/v1/${secretPath}`, {
      headers: { "X-Vault-Token": vaultToken },
      signal: AbortSignal.timeout(8000),
    });
    if (!resp.ok) return null;
    const payload = await resp.json();
    const data = payload?.data?.data ?? payload?.data ?? {};
    return data[field] || null;
  } catch {
    return null;
  }
}

/**
 * Generate .env file content for a profile + credentials object.
 * Only writes fields that are present — omitted fields are not included.
 */
export function generateEnvContent(profile, creds) {
  const backend = creds?.secretsBackend || "env";
  const isVault = backend === "vault";
  const lines = [
    `# Audrique Connection: ${profile.label}`,
    `# Generated by Scenario Studio`,
    ``,
    `# Security / secrets`,
    `SECRETS_BACKEND=${backend}`,
    `REGULATED_MODE=${isVault ? "true" : "false"}`,
  ];

  if (isVault) {
    lines.push(`VAULT_ADDR=${creds.vaultAddr || ""}`);
    // VAULT_TOKEN is stored in .vault-auth.json, NOT in .env
  }

  const sfAuthMethod = creds?.sfAuthMethod || "password";
  lines.push(
    ``,
    `# Salesforce`,
    `SF_LOGIN_URL=${profile.salesforce?.loginUrl || "https://login.salesforce.com"}`,
    `SF_AUTH_METHOD=${sfAuthMethod}`,
  );

  if (sfAuthMethod === "oauth") {
    if (isVault) {
      const basePath = creds?.vaultBasePath || `secret/data/voice/${profile.id}/salesforce`;
      lines.push(`SF_OAUTH_CONSUMER_KEY=`);
      lines.push(`SF_OAUTH_CONSUMER_KEY_REF=${creds?.oauthConsumerKeyRef || `${basePath}#consumer_key`}`);
      lines.push(`SF_OAUTH_CONSUMER_SECRET=`);
      lines.push(`SF_OAUTH_REFRESH_TOKEN=`);
      lines.push(`SF_OAUTH_REFRESH_TOKEN_REF=${creds?.oauthRefreshTokenRef || `${basePath}#refresh_token`}`);
    } else {
      // Accept both old (sfOauthConsumerKey) and new (oauthConsumerKey) field names
      lines.push(`SF_OAUTH_CONSUMER_KEY=${creds?.oauthConsumerKey || creds?.sfOauthConsumerKey || ""}`);
      lines.push(`SF_OAUTH_CONSUMER_SECRET=${creds?.oauthConsumerSecret || creds?.sfOauthConsumerSecret || ""}`);
      lines.push(`SF_OAUTH_REFRESH_TOKEN=${creds?.oauthRefreshToken || ""}`);
    }
    lines.push(`SF_OAUTH_CALLBACK_URL=${creds?.sfOauthCallbackUrl || "http://localhost:4200/oauth/callback"}`);
  } else if (isVault) {
    lines.push(`SF_USERNAME_REF=${creds?.sfUsernameRef || ""}`);
    lines.push(`SF_PASSWORD_REF=${creds?.sfPasswordRef || ""}`);
  } else {
    lines.push(`SF_USERNAME=${creds?.sfUsername || ""}`);
    lines.push(`SF_PASSWORD=${creds?.sfPassword || ""}`);
  }

  lines.push(`SF_APP_NAME=${profile.salesforce?.appName || "Service Console"}`);
  if (sfAuthMethod === "oauth" && isVault) {
    const basePath = creds?.vaultBasePath || `secret/data/voice/${profile.id}/salesforce`;
    lines.push(`SF_INSTANCE_URL=`);
    lines.push(`SF_INSTANCE_URL_REF=${creds?.sfInstanceUrlRef || `${basePath}#instance_url`}`);
  } else {
    lines.push(`SF_INSTANCE_URL=${creds?.sfInstanceUrl || ""}`);
  }
  lines.push(
    `SF_STORAGE_STATE=.auth/sf-${profile.id}.json`,
    `SF_SKIP_LOGIN=${sfAuthMethod === "oauth" && isVault ? "false" : "true"}`,
    ``,
    `# Voice test behavior`,
    `CALL_TRIGGER_MODE=connect_ccp`,
    `OMNI_TARGET_STATUS=Available`,
    `VOICE_RING_TIMEOUT_SEC=180`,
    ``,
    `# Amazon Connect`,
    `CONNECT_INSTANCE_ALIAS=${profile.connect?.instanceAlias || ""}`,
  );

  if (isVault) {
    lines.push(`AWS_USERNAME=`);
    lines.push(`AWS_USERNAME_REF=${creds?.awsUsernameRef || ""}`);
    lines.push(`AWS_PASSWORD=`);
    lines.push(`AWS_PASSWORD_REF=${creds?.awsPasswordRef || ""}`);
    lines.push(`AWS_ACCOUNT_ID=`);
    lines.push(`AWS_ACCOUNT_ID_REF=${creds?.awsAccountIdRef || ""}`);
    lines.push(`# Connect Federation API (headless auth, no browser sign-in)`);
    lines.push(`AWS_ACCESS_KEY_ID=`);
    lines.push(`AWS_ACCESS_KEY_ID_REF=${creds?.awsAccessKeyIdRef || ""}`);
    lines.push(`AWS_SECRET_ACCESS_KEY=`);
    lines.push(`AWS_SECRET_ACCESS_KEY_REF=${creds?.awsSecretAccessKeyRef || ""}`);
    lines.push(`CONNECT_INSTANCE_ID=`);
    lines.push(`CONNECT_INSTANCE_ID_REF=${creds?.connectInstanceIdRef || ""}`);
  } else {
    lines.push(`AWS_USERNAME=${creds?.awsUsername || ""}`);
    lines.push(`AWS_PASSWORD=${creds?.awsPassword || ""}`);
    lines.push(`AWS_ACCOUNT_ID=${creds?.awsAccountId || ""}`);
  }

  lines.push(
    `CONNECT_CONSOLE_REGION=${profile.connect?.region || "us-west-2"}`,
    `CONNECT_STORAGE_STATE=.auth/connect-ccp-${profile.id}.json`,
    `CONNECT_AUTO_AWS_LOGIN=true`,
    ``,
    `# Twilio (optional)`,
  );

  if (isVault) {
    lines.push(`TWILIO_ACCOUNT_SID=`);
    lines.push(`TWILIO_ACCOUNT_SID_REF=${creds?.twilioSidRef || ""}`);
    lines.push(`TWILIO_AUTH_TOKEN=`);
    lines.push(`TWILIO_AUTH_TOKEN_REF=${creds?.twilioTokenRef || ""}`);
    lines.push(`TWILIO_FROM_NUMBER=${creds?.twilioFromNumber || ""}`);
    lines.push(`TWILIO_FROM_NUMBER_REF=`);
    lines.push(`CONNECT_ENTRYPOINT_NUMBER=${creds?.connectEntrypoint || ""}`);
    lines.push(`CONNECT_ENTRYPOINT_NUMBER_REF=`);
  } else {
    lines.push(`TWILIO_ACCOUNT_SID=${creds?.twilioSid || ""}`);
    lines.push(`TWILIO_AUTH_TOKEN=${creds?.twilioToken || ""}`);
    lines.push(`TWILIO_FROM_NUMBER=${creds?.twilioFromNumber || ""}`);
    lines.push(`CONNECT_ENTRYPOINT_NUMBER=${creds?.connectEntrypoint || ""}`);
  }

  // AI Providers (NL Caller — optional)
  const hasGemini = isVault ? creds?.geminiApiKeyRef : creds?.geminiApiKey;
  if (hasGemini) {
    lines.push(`# AI Providers (NL Caller)`);
    if (isVault) {
      lines.push(`GEMINI_API_KEY=`);
      lines.push(`GEMINI_API_KEY_REF=${creds?.geminiApiKeyRef || ""}`);
    } else {
      lines.push(`GEMINI_API_KEY=${creds?.geminiApiKey || ""}`);
    }
  }

  lines.push(``);

  return lines.join("\n");
}
