#!/usr/bin/env node
/**
 * Audrique Scenario Studio — Express server
 *
 * Serves the interactive scenario builder UI and provides API routes
 * for reading profiles, suites, and saving generated scenarios.
 *
 * Usage:
 *   node webapp/server.mjs
 *   node webapp/server.mjs --port 4200
 */

import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");

// ── CLI args ────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const portFlag = args.indexOf("--port");
const PORT = portFlag >= 0 ? parseInt(args[portFlag + 1], 10) : 4200;

// ── Helpers ─────────────────────────────────────────────────────────────────

function readJsonFile(filePath) {
  const resolved = path.resolve(PROJECT_ROOT, filePath);
  if (!fs.existsSync(resolved)) return null;
  return JSON.parse(fs.readFileSync(resolved, "utf8"));
}

function writeJsonFile(filePath, data) {
  const resolved = path.resolve(PROJECT_ROOT, filePath);
  fs.mkdirSync(path.dirname(resolved), { recursive: true });
  fs.writeFileSync(resolved, JSON.stringify(data, null, 2) + "\n");
}

function slugify(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function parseBody(req) {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch (err) {
        reject(new Error("Invalid JSON body"));
      }
    });
    req.on("error", reject);
  });
}

function sendJson(res, status, data) {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
  });
  res.end(JSON.stringify(data));
}

function sendFile(res, filePath, contentType) {
  const resolved = path.resolve(__dirname, filePath);
  if (!fs.existsSync(resolved)) {
    res.writeHead(404);
    res.end("Not found");
    return;
  }
  res.writeHead(200, { "Content-Type": contentType });
  fs.createReadStream(resolved).pipe(res);
}

// ── MIME types ───────────────────────────────────────────────────────────────
const MIME = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "application/javascript",
  ".mjs": "application/javascript",
  ".json": "application/json",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
};

// ── .env file helpers ────────────────────────────────────────────────────────

const SENSITIVE_PATTERNS = [/PASSWORD/i, /TOKEN/i, /SECRET/i, /API_KEY/i, /PRIVATE_KEY/i, /AUTH_TOKEN/i];
const SENSITIVE_KEYS = new Set([
  "SF_PASSWORD", "SF_EMAIL_CODE", "AWS_PASSWORD",
  "TWILIO_AUTH_TOKEN", "VAULT_TOKEN",
]);

const NON_SENSITIVE_KEYS = new Set(["SECRETS_BACKEND", "REGULATED_MODE"]);

function isSensitiveKey(key) {
  if (NON_SENSITIVE_KEYS.has(key)) return false;
  if (SENSITIVE_KEYS.has(key)) return true;
  if (key.endsWith("_REF")) return false; // Vault refs are not sensitive
  return SENSITIVE_PATTERNS.some((p) => p.test(key));
}

function parseEnvFile(filePath) {
  const resolved = path.resolve(PROJECT_ROOT, filePath);
  if (!fs.existsSync(resolved)) return null;
  const content = fs.readFileSync(resolved, "utf8");
  const env = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx < 1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    env[key] = val;
  }
  return env;
}

function maskSensitiveValues(envMap) {
  const masked = { ...envMap };
  for (const key of Object.keys(masked)) {
    if (isSensitiveKey(key) && masked[key]) {
      masked[key] = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
    }
  }
  return masked;
}

function generateEnvContent(profile, creds) {
  const backend = creds?.secretsBackend || "env";
  const isVault = backend === "vault";
  const lines = [
    `# Audrique Connection: ${profile.label}`,
    `# Generated by Scenario Studio`,
    ``,
    `# Security / secrets`,
    `SECRETS_BACKEND=${backend}`,
    `REGULATED_MODE=${isVault ? "true" : "false"}`,
  ];

  if (isVault) {
    lines.push(`VAULT_ADDR=${creds.vaultAddr || ""}`);
    lines.push(`VAULT_TOKEN=${creds.vaultToken || ""}`);
  }

  lines.push(
    ``,
    `# Salesforce`,
    `SF_LOGIN_URL=${profile.salesforce?.loginUrl || "https://login.salesforce.com"}`,
  );

  if (isVault) {
    lines.push(`SF_USERNAME_REF=${creds.sfUsernameRef || ""}`);
    lines.push(`SF_PASSWORD_REF=${creds.sfPasswordRef || ""}`);
  } else {
    lines.push(`SF_USERNAME=${creds?.sfUsername || ""}`);
    lines.push(`SF_PASSWORD=${creds?.sfPassword || ""}`);
  }

  lines.push(
    `SF_APP_NAME=${profile.salesforce?.appName || "Service Console"}`,
    `SF_INSTANCE_URL=`,
    `SF_STORAGE_STATE=.auth/sf-${profile.id}.json`,
    `SF_SKIP_LOGIN=true`,
    ``,
    `# Voice test behavior`,
    `CALL_TRIGGER_MODE=connect_ccp`,
    `OMNI_TARGET_STATUS=Available`,
    `VOICE_RING_TIMEOUT_SEC=90`,
    ``,
    `# Amazon Connect`,
    `CONNECT_INSTANCE_ALIAS=${profile.connect?.instanceAlias || ""}`,
  );

  if (isVault) {
    lines.push(`AWS_USERNAME_REF=${creds.awsUsernameRef || ""}`);
    lines.push(`AWS_PASSWORD_REF=${creds.awsPasswordRef || ""}`);
    lines.push(`AWS_ACCOUNT_ID_REF=${creds.awsAccountIdRef || ""}`);
  } else {
    lines.push(`AWS_USERNAME=${creds?.awsUsername || ""}`);
    lines.push(`AWS_PASSWORD=${creds?.awsPassword || ""}`);
    lines.push(`AWS_ACCOUNT_ID=${creds?.awsAccountId || ""}`);
  }

  lines.push(
    `CONNECT_CONSOLE_REGION=${profile.connect?.region || "us-west-2"}`,
    `CONNECT_STORAGE_STATE=.auth/connect-ccp-${profile.id}.json`,
    `CONNECT_AUTO_AWS_LOGIN=true`,
    ``,
    `# Twilio (optional)`,
  );

  if (isVault) {
    lines.push(`TWILIO_ACCOUNT_SID_REF=${creds.twilioSidRef || ""}`);
    lines.push(`TWILIO_AUTH_TOKEN_REF=${creds.twilioTokenRef || ""}`);
  } else {
    lines.push(`TWILIO_ACCOUNT_SID=${creds?.twilioSid || ""}`);
    lines.push(`TWILIO_AUTH_TOKEN=${creds?.twilioToken || ""}`);
  }

  lines.push(
    `TWILIO_FROM_NUMBER=${creds?.twilioFromNumber || ""}`,
    `CONNECT_ENTRYPOINT_NUMBER=${creds?.connectEntrypoint || ""}`,
    ``,
  );

  return lines.join("\n");
}

// Backward-compatible wrapper
function generateSkeletonEnv(profile) {
  return generateEnvContent(profile, null);
}

// ── API Routes ──────────────────────────────────────────────────────────────

async function handleApi(req, res) {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const pathname = url.pathname;

  // CORS preflight
  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    });
    res.end();
    return true;
  }

  // GET /api/profiles — list all customer profiles (with auth status)
  if (pathname === "/api/profiles" && req.method === "GET") {
    const data = readJsonFile("instances/profiles.json") || { profiles: [] };
    // Annotate each profile with credential status
    for (const p of data.profiles) {
      const envMap = parseEnvFile(p.envFile);
      if (!envMap) {
        p._authStatus = "missing";
      } else {
        const backend = (envMap.SECRETS_BACKEND || "env").toLowerCase();
        p._authBackend = backend;
        if (backend === "vault") {
          p._authStatus = (envMap.VAULT_ADDR && envMap.SF_PASSWORD_REF) ? "configured" : "incomplete";
        } else {
          p._authStatus = (envMap.SF_USERNAME && envMap.SF_PASSWORD) ? "configured" : "incomplete";
        }
      }
    }
    sendJson(res, 200, data);
    return true;
  }

  // GET /api/suites — list available suite files
  if (pathname === "/api/suites" && req.method === "GET") {
    const suiteDir = path.resolve(PROJECT_ROOT, "scenarios/e2e");
    const files = fs.existsSync(suiteDir)
      ? fs.readdirSync(suiteDir).filter((f) => f.endsWith(".json"))
      : [];
    const suites = files.map((f) => {
      const data = readJsonFile(`scenarios/e2e/${f}`);
      return {
        file: `scenarios/e2e/${f}`,
        name: data?.name || f,
        version: data?.version || 1,
        scenarioCount: data?.scenarios?.length || 0,
        connectionSetId: data?.connectionSetId || null,
      };
    });
    sendJson(res, 200, { suites });
    return true;
  }

  // GET /api/suite?file=scenarios/e2e/full-suite-v2.json — load a suite
  if (pathname === "/api/suite" && req.method === "GET") {
    const file = url.searchParams.get("file");
    if (!file) {
      sendJson(res, 400, { error: "Missing ?file= parameter" });
      return true;
    }
    const data = readJsonFile(file);
    if (!data) {
      sendJson(res, 404, { error: `Suite not found: ${file}` });
      return true;
    }
    sendJson(res, 200, data);
    return true;
  }

  // POST /api/scenario — save a scenario to a suite
  if (pathname === "/api/scenario" && req.method === "POST") {
    const body = await parseBody(req);
    const { scenario, suiteFile } = body;
    if (!scenario || !suiteFile) {
      sendJson(res, 400, { error: "Missing scenario or suiteFile" });
      return true;
    }

    const resolved = path.resolve(PROJECT_ROOT, suiteFile);
    let suite;
    if (fs.existsSync(resolved)) {
      suite = JSON.parse(fs.readFileSync(resolved, "utf8"));
      const existing = suite.scenarios.findIndex((s) => s.id === scenario.id);
      if (existing >= 0) {
        suite.scenarios[existing] = scenario;
      } else {
        suite.scenarios.push(scenario);
      }
    } else {
      suite = {
        name: "Custom Test Suite",
        version: 2,
        stopOnFailure: false,
        defaults: {
          callTrigger: { mode: "connect_ccp" },
          timeouts: {
            ringSec: 90,
            supervisorQueueSec: 90,
            supervisorAgentOfferSec: 90,
            offerAfterQueueSec: 120,
          },
        },
        scenarios: [scenario],
      };
    }

    writeJsonFile(suiteFile, suite);
    sendJson(res, 200, {
      message: `Scenario "${scenario.id}" saved to ${suiteFile}`,
      scenarioCount: suite.scenarios.length,
    });
    return true;
  }

  // DELETE /api/scenario — remove a scenario from a suite
  if (pathname === "/api/scenario" && req.method === "DELETE") {
    const body = await parseBody(req);
    const { scenarioId, suiteFile } = body;
    if (!scenarioId || !suiteFile) {
      sendJson(res, 400, { error: "Missing scenarioId or suiteFile" });
      return true;
    }
    const data = readJsonFile(suiteFile);
    if (!data) {
      sendJson(res, 404, { error: `Suite not found: ${suiteFile}` });
      return true;
    }
    data.scenarios = data.scenarios.filter((s) => s.id !== scenarioId);
    writeJsonFile(suiteFile, data);
    sendJson(res, 200, {
      message: `Scenario "${scenarioId}" removed`,
      scenarioCount: data.scenarios.length,
    });
    return true;
  }

  // GET /api/vocabulary — get cached org vocabulary for a profile
  if (pathname === "/api/vocabulary" && req.method === "GET") {
    const params = new URLSearchParams(req.url.split("?")[1] || "");
    const profileId = params.get("profile") || "personal";
    const cachePath = path.resolve(
      PROJECT_ROOT,
      `.cache/org-vocabulary-${profileId}.json`
    );
    if (fs.existsSync(cachePath)) {
      const data = JSON.parse(fs.readFileSync(cachePath, "utf8"));
      sendJson(res, 200, { cached: true, vocabulary: data });
    } else {
      sendJson(res, 200, { cached: false, vocabulary: null });
    }
    return true;
  }

  // GET /api/env-preview — dry-run: show env vars for a scenario
  if (pathname === "/api/env-preview" && req.method === "POST") {
    const body = await parseBody(req);
    const { scenario, defaults } = body;
    if (!scenario) {
      sendJson(res, 400, { error: "Missing scenario" });
      return true;
    }
    // Dynamically import the bridge
    const bridge = await import(
      path.resolve(PROJECT_ROOT, "scripts/scenario-bridge.mjs")
    );
    const env = bridge.scenarioToEnv(scenario, defaults || {});
    sendJson(res, 200, { env });
    return true;
  }

  // ── Suite management ────────────────────────────────────────────────────

  // POST /api/suite — create a new suite
  if (pathname === "/api/suite" && req.method === "POST") {
    const body = await parseBody(req);
    const { name, connectionSetId } = body;
    if (!name || !name.trim()) {
      sendJson(res, 400, { error: "Suite name is required" });
      return true;
    }
    let slug = slugify(name);
    let filePath = `scenarios/e2e/${slug}.json`;
    let counter = 2;
    while (fs.existsSync(path.resolve(PROJECT_ROOT, filePath))) {
      filePath = `scenarios/e2e/${slug}-${counter}.json`;
      counter++;
    }
    const suite = {
      name: name.trim(),
      version: 2,
      ...(connectionSetId ? { connectionSetId } : {}),
      stopOnFailure: false,
      defaults: {
        callTrigger: { mode: "connect_ccp" },
        timeouts: { ringSec: 90, supervisorQueueSec: 90, supervisorAgentOfferSec: 90, offerAfterQueueSec: 120 },
      },
      scenarios: [],
    };
    writeJsonFile(filePath, suite);
    sendJson(res, 200, { file: filePath, name: suite.name });
    return true;
  }

  // PUT /api/suite — update suite metadata (rename, change connectionSetId)
  if (pathname === "/api/suite" && req.method === "PUT") {
    const body = await parseBody(req);
    const { file, name, connectionSetId } = body;
    if (!file) {
      sendJson(res, 400, { error: "Missing file parameter" });
      return true;
    }
    const data = readJsonFile(file);
    if (!data) {
      sendJson(res, 404, { error: `Suite not found: ${file}` });
      return true;
    }
    if (name !== undefined) data.name = name.trim();
    if (connectionSetId !== undefined) {
      if (connectionSetId) {
        data.connectionSetId = connectionSetId;
      } else {
        delete data.connectionSetId;
      }
    }
    writeJsonFile(file, data);
    sendJson(res, 200, { message: "Suite updated" });
    return true;
  }

  // DELETE /api/suite — delete a suite file
  if (pathname === "/api/suite" && req.method === "DELETE") {
    const body = await parseBody(req);
    const { file } = body;
    if (!file) {
      sendJson(res, 400, { error: "Missing file parameter" });
      return true;
    }
    const resolved = path.resolve(PROJECT_ROOT, file);
    if (!fs.existsSync(resolved)) {
      sendJson(res, 404, { error: `Suite not found: ${file}` });
      return true;
    }
    fs.unlinkSync(resolved);
    sendJson(res, 200, { message: `Suite deleted: ${file}` });
    return true;
  }

  // ── Profile / Connection Set management ────────────────────────────────

  // POST /api/profile — create a new connection set
  if (pathname === "/api/profile" && req.method === "POST") {
    const body = await parseBody(req);
    const { label, customer, salesforce, connect } = body;
    if (!label || !label.trim()) {
      sendJson(res, 400, { error: "Connection label is required" });
      return true;
    }
    const profilesData = readJsonFile("instances/profiles.json") || { defaultInstance: "", profiles: [] };
    const id = slugify(label);
    if (profilesData.profiles.some((p) => p.id === id)) {
      sendJson(res, 409, { error: `Connection "${id}" already exists` });
      return true;
    }
    const envFile = `instances/${id}.env`;
    const profile = {
      id,
      label: label.trim(),
      customer: customer?.trim() || "",
      envFile,
      salesforce: {
        loginUrl: salesforce?.loginUrl || "https://login.salesforce.com",
        appName: salesforce?.appName || "Service Console",
      },
      connect: {
        region: connect?.region || "us-west-2",
        instanceAlias: connect?.instanceAlias || "",
      },
      discovery: { autoDiscover: true, cacheFile: `.cache/org-vocabulary-${id}.json`, cacheTtlMinutes: 60 },
      vocabulary: {
        omniTargetStatus: null,
        queues: {},
        skills: {},
        ivrFlows: {},
        routing: { defaultType: "queue", skillBasedEnabled: false },
        supervisor: { surfaceName: null, appName: null },
        selectorOverrides: {},
      },
    };
    profilesData.profiles.push(profile);
    if (!profilesData.defaultInstance) profilesData.defaultInstance = id;
    writeJsonFile("instances/profiles.json", profilesData);

    // Generate skeleton .env file
    const envContent = generateSkeletonEnv(profile);
    const envResolved = path.resolve(PROJECT_ROOT, envFile);
    fs.mkdirSync(path.dirname(envResolved), { recursive: true });
    fs.writeFileSync(envResolved, envContent);

    sendJson(res, 200, { id, envFile });
    return true;
  }

  // PUT /api/profile — update a connection set
  if (pathname === "/api/profile" && req.method === "PUT") {
    const body = await parseBody(req);
    const { id, label, customer, salesforce, connect } = body;
    if (!id) {
      sendJson(res, 400, { error: "Missing profile id" });
      return true;
    }
    const profilesData = readJsonFile("instances/profiles.json");
    if (!profilesData) {
      sendJson(res, 404, { error: "No profiles found" });
      return true;
    }
    const profile = profilesData.profiles.find((p) => p.id === id);
    if (!profile) {
      sendJson(res, 404, { error: `Profile not found: ${id}` });
      return true;
    }
    if (label !== undefined) profile.label = label.trim();
    if (customer !== undefined) profile.customer = customer.trim();
    if (salesforce) {
      if (salesforce.loginUrl) profile.salesforce.loginUrl = salesforce.loginUrl;
      if (salesforce.appName !== undefined) profile.salesforce.appName = salesforce.appName;
    }
    if (connect) {
      if (connect.instanceAlias !== undefined) profile.connect.instanceAlias = connect.instanceAlias;
      if (connect.region) profile.connect.region = connect.region;
    }
    writeJsonFile("instances/profiles.json", profilesData);
    sendJson(res, 200, { message: "Profile updated" });
    return true;
  }

  // DELETE /api/profile — delete a connection set
  if (pathname === "/api/profile" && req.method === "DELETE") {
    const body = await parseBody(req);
    const { id } = body;
    if (!id) {
      sendJson(res, 400, { error: "Missing profile id" });
      return true;
    }
    const profilesData = readJsonFile("instances/profiles.json");
    if (!profilesData) {
      sendJson(res, 404, { error: "No profiles found" });
      return true;
    }
    // Check if any suite references this connection
    const suiteDir = path.resolve(PROJECT_ROOT, "scenarios/e2e");
    if (fs.existsSync(suiteDir)) {
      const suiteFiles = fs.readdirSync(suiteDir).filter((f) => f.endsWith(".json"));
      for (const sf of suiteFiles) {
        const suite = readJsonFile(`scenarios/e2e/${sf}`);
        if (suite?.connectionSetId === id) {
          sendJson(res, 409, { error: `Cannot delete: suite "${suite.name}" uses this connection` });
          return true;
        }
      }
    }
    const deletedProfile = profilesData.profiles.find((p) => p.id === id);
    profilesData.profiles = profilesData.profiles.filter((p) => p.id !== id);
    if (profilesData.defaultInstance === id) {
      profilesData.defaultInstance = profilesData.profiles[0]?.id || "";
    }
    writeJsonFile("instances/profiles.json", profilesData);
    // Clean up the skeleton .env file if it exists
    if (deletedProfile?.envFile) {
      const envPath = path.resolve(PROJECT_ROOT, deletedProfile.envFile);
      if (fs.existsSync(envPath)) fs.unlinkSync(envPath);
    }
    sendJson(res, 200, { message: `Connection "${id}" deleted` });
    return true;
  }

  // ── Profile env / credentials management ───────────────────────────────

  // GET /api/profile/env?id=<profileId> — read .env values for editing
  if (pathname === "/api/profile/env" && req.method === "GET") {
    const profileId = url.searchParams.get("id");
    if (!profileId) {
      sendJson(res, 400, { error: "Missing ?id= parameter" });
      return true;
    }
    const profilesData = readJsonFile("instances/profiles.json");
    const profile = profilesData?.profiles?.find((p) => p.id === profileId);
    if (!profile) {
      sendJson(res, 404, { error: `Profile not found: ${profileId}` });
      return true;
    }
    const envMap = parseEnvFile(profile.envFile);
    if (!envMap) {
      sendJson(res, 200, { backend: "env", env: {}, configured: false });
      return true;
    }
    const backend = (envMap.SECRETS_BACKEND || "env").toLowerCase();
    const masked = backend === "vault" ? envMap : maskSensitiveValues(envMap);
    // Check if credentials are configured (non-empty sensitive fields)
    let configured = false;
    if (backend === "vault") {
      configured = !!(envMap.VAULT_ADDR && envMap.SF_PASSWORD_REF);
    } else {
      configured = !!(envMap.SF_USERNAME && envMap.SF_PASSWORD);
    }
    sendJson(res, 200, { backend, env: masked, configured });
    return true;
  }

  // POST /api/profile/env — write credentials to .env file
  if (pathname === "/api/profile/env" && req.method === "POST") {
    const body = await parseBody(req);
    const { id, credentials } = body;
    if (!id) {
      sendJson(res, 400, { error: "Missing profile id" });
      return true;
    }
    const profilesData = readJsonFile("instances/profiles.json");
    const profile = profilesData?.profiles?.find((p) => p.id === id);
    if (!profile) {
      sendJson(res, 404, { error: `Profile not found: ${id}` });
      return true;
    }
    const envContent = generateEnvContent(profile, credentials || {});
    const envResolved = path.resolve(PROJECT_ROOT, profile.envFile);
    fs.mkdirSync(path.dirname(envResolved), { recursive: true });
    fs.writeFileSync(envResolved, envContent);
    sendJson(res, 200, { message: "Credentials saved", envFile: profile.envFile });
    return true;
  }

  // POST /api/vault/test — test vault connectivity
  if (pathname === "/api/vault/test" && req.method === "POST") {
    const body = await parseBody(req);
    const { vaultAddr, vaultToken, testRef } = body;
    if (!vaultAddr || !vaultToken) {
      sendJson(res, 400, { error: "Vault address and token are required" });
      return true;
    }
    try {
      // Test basic connectivity: GET /v1/sys/health
      const healthUrl = `${vaultAddr.replace(/\/+$/, "")}/v1/sys/health`;
      const healthResp = await fetch(healthUrl, {
        method: "GET",
        headers: { "X-Vault-Token": vaultToken },
        signal: AbortSignal.timeout(10000),
      });
      if (!healthResp.ok) {
        const text = await healthResp.text().catch(() => "");
        sendJson(res, 200, {
          success: false,
          error: `Vault returned HTTP ${healthResp.status}: ${text.slice(0, 200)}`,
        });
        return true;
      }
      const health = await healthResp.json();
      const result = { success: true, sealed: health.sealed, version: health.version };

      // Optionally test a specific secret reference
      if (testRef) {
        const ref = testRef.trim();
        const hashIdx = ref.lastIndexOf("#");
        let vaultPath, field;
        if (hashIdx > 0) {
          vaultPath = ref.slice(0, hashIdx);
          field = ref.slice(hashIdx + 1);
        } else {
          vaultPath = ref;
          field = "value";
        }
        const secretUrl = `${vaultAddr.replace(/\/+$/, "")}/v1/${vaultPath.replace(/^\/+/, "")}`;
        const secretResp = await fetch(secretUrl, {
          method: "GET",
          headers: { "X-Vault-Token": vaultToken },
          signal: AbortSignal.timeout(10000),
        });
        if (secretResp.ok) {
          const payload = await secretResp.json();
          const data = payload?.data?.data ?? payload?.data ?? {};
          result.secretAccessible = field in data;
          result.secretField = field;
        } else {
          result.secretAccessible = false;
          result.secretError = `HTTP ${secretResp.status}`;
        }
      }

      sendJson(res, 200, result);
    } catch (err) {
      sendJson(res, 200, {
        success: false,
        error: err.message || "Failed to connect to Vault",
      });
    }
    return true;
  }

  // ── Run management ──────────────────────────────────────────────────────

  // POST /api/run — start a suite run, returns run ID
  if (pathname === "/api/run" && req.method === "POST") {
    const body = await parseBody(req);
    const suiteFile = body.suiteFile || "scenarios/e2e/full-suite-v2.json";
    const dryRun = body.dryRun === true;
    // Resolve instance: explicit override > suite connectionSetId > env var
    let instance = body.instance || "";
    if (!instance) {
      const suiteData = readJsonFile(suiteFile);
      if (suiteData?.connectionSetId) instance = suiteData.connectionSetId;
    }
    if (!instance) instance = process.env.INSTANCE || "";

    if (activeRun) {
      sendJson(res, 409, { error: "A run is already in progress", runId: activeRun.id });
      return true;
    }

    const runId = `run-${Date.now()}`;
    const env = {
      ...process.env,
      E2E_SUITE_FILE: suiteFile,
      FORCE_COLOR: "0",
    };
    if (dryRun) env.E2E_SUITE_DRY_RUN = "true";
    if (instance) env.INSTANCE = instance;

    const child = spawn("node", [path.join(PROJECT_ROOT, "scripts/run-instance-e2e-suite.mjs")], {
      cwd: PROJECT_ROOT,
      env,
      stdio: ["ignore", "pipe", "pipe"],
    });

    activeRun = {
      id: runId,
      suiteFile,
      dryRun,
      startedAt: new Date().toISOString(),
      status: "running",
      child,
      listeners: new Set(),
      lines: [],
    };

    const broadcast = (data) => {
      const msg = `data: ${JSON.stringify(data)}\n\n`;
      activeRun.lines.push(data);
      for (const listener of activeRun.listeners) {
        try { listener.write(msg); } catch (_) { /* client gone */ }
      }
    };

    child.stdout.on("data", (chunk) => {
      const text = chunk.toString();
      for (const line of text.split("\n")) {
        if (line.length === 0) continue;
        // Parse scenario status from suite runner output
        const scenarioMatch = line.match(/^(?:Running|PASS|FAIL|SKIP)\b/);
        broadcast({
          type: scenarioMatch ? "scenario" : "log",
          text: line,
          ts: Date.now(),
        });
      }
    });

    child.stderr.on("data", (chunk) => {
      const text = chunk.toString();
      for (const line of text.split("\n")) {
        if (line.length === 0) continue;
        broadcast({ type: "error", text: line, ts: Date.now() });
      }
    });

    child.on("close", (code) => {
      const status = code === 0 ? "passed" : "failed";
      broadcast({ type: "done", code, status, ts: Date.now() });
      if (activeRun) {
        activeRun.status = status;
        activeRun.exitCode = code;
        // Clean up listeners after a delay
        setTimeout(() => {
          if (activeRun?.id === runId) {
            for (const listener of activeRun.listeners) {
              try { listener.end(); } catch (_) {}
            }
            activeRun = null;
          }
        }, 5000);
      }
    });

    sendJson(res, 200, { runId, suiteFile, dryRun, status: "running" });
    return true;
  }

  // GET /api/run/stream — SSE stream of live output
  if (pathname === "/api/run/stream" && req.method === "GET") {
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      "Connection": "keep-alive",
      "Access-Control-Allow-Origin": "*",
    });

    if (!activeRun) {
      res.write(`data: ${JSON.stringify({ type: "error", text: "No active run" })}\n\n`);
      res.end();
      return true;
    }

    // Send buffered lines first (for late-joining clients)
    for (const line of activeRun.lines) {
      res.write(`data: ${JSON.stringify(line)}\n\n`);
    }

    activeRun.listeners.add(res);
    req.on("close", () => {
      activeRun?.listeners.delete(res);
    });

    return true;
  }

  // POST /api/run/stop — stop the active run
  if (pathname === "/api/run/stop" && req.method === "POST") {
    if (!activeRun) {
      sendJson(res, 404, { error: "No active run" });
      return true;
    }
    activeRun.child.kill("SIGTERM");
    sendJson(res, 200, { message: "Run stopped", runId: activeRun.id });
    return true;
  }

  // GET /api/run/status — check current run status
  if (pathname === "/api/run/status" && req.method === "GET") {
    if (!activeRun) {
      sendJson(res, 200, { running: false });
      return true;
    }
    sendJson(res, 200, {
      running: activeRun.status === "running",
      runId: activeRun.id,
      suiteFile: activeRun.suiteFile,
      dryRun: activeRun.dryRun,
      status: activeRun.status,
      startedAt: activeRun.startedAt,
      lineCount: activeRun.lines.length,
    });
    return true;
  }

  return false;
}

// ── Active run state ────────────────────────────────────────────────────────
let activeRun = null;

// ── HTTP Server ─────────────────────────────────────────────────────────────

const server = http.createServer(async (req, res) => {
  try {
    // API routes
    if (req.url.startsWith("/api/")) {
      const handled = await handleApi(req, res);
      if (handled) return;
      sendJson(res, 404, { error: "Unknown API endpoint" });
      return;
    }

    // Static files
    let filePath = req.url === "/" ? "/index.html" : req.url;
    // Strip query strings
    filePath = filePath.split("?")[0];
    const ext = path.extname(filePath);
    const contentType = MIME[ext] || "application/octet-stream";
    sendFile(res, `public${filePath}`, contentType);
  } catch (err) {
    console.error("Server error:", err);
    sendJson(res, 500, { error: err.message });
  }
});

server.listen(PORT, () => {
  console.log("");
  console.log("  ┌──────────────────────────────────────────────┐");
  console.log("  │                                              │");
  console.log("  │   Audrique Scenario Studio                   │");
  console.log(`  │   http://localhost:${PORT}                      │`);
  console.log("  │                                              │");
  console.log("  │   Press Ctrl+C to stop                       │");
  console.log("  │                                              │");
  console.log("  └──────────────────────────────────────────────┘");
  console.log("");
});
